mergebot:
  # -- whether tls is enabled, certificate will be issued by letsencrypt
  # you have to provide tlsDomain 
  tlsEnabled: false
  # -- if tlsEnabled is true, you have to set tlsDomain
  tlsDomain: ""
  # -- gitlab token
  gitlabToken: ""
  # -- gitlab url in case it is not gitlab cloud
  gitlabURL: ""
  # -- max repo size for !update, !merge command
  gitlabMaxRepoSize: 500Mb # 1Gb, 100Kb

  gitlabSecret:
    # -- whether to use secret, it must contain gitlab-token secret.
    enabled: false
    # -- secret name
    # k8s secret where gitlab token is stored, gitlabToken will be ignored, secret example:
    # data:
    #   gitlab-token: "secret"
    name: "merge-bot"
  # -- sentry
  sentryEnabled: true
  # -- debug mode
  debug: false
  envFrom: []

# @ignored
replicaCount: 1

# -- whether prometheus metrics are exposed
# port is 8081, port name is metrics
metrics:
  enabled: true


# @ignored
image:
  repository: gasoid/merge-bot
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


# @ignored
imagePullSecrets: []
# @ignored
nameOverride: ""
# @ignored
fullnameOverride: ""

# @ignored
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# @ignored
podAnnotations: {}

# @ignored
podLabels: {}

# @ignored
podSecurityContext: {}

# @ignored
securityContext: {}

# @ignored
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080

# @ignored
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /mergebot
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# @ignored
resources:
  requests:
    memory: "50Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "500m"

# @ignored
livenessProbe:
  httpGet:
    path: /healthy
    port: http
  periodSeconds: 30

# @ignored
readinessProbe:
  httpGet:
    path: /healthy
    port: http


# @ignored
nodeSelector: {}

# @ignored
tolerations: []

# @ignored
affinity: {}
